version: '3.6'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    networks:
      - api

networks:
  api:
    external:
      name: api
