version: '3.6'

services:
  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    env_file:
      - ./backend/dev.env
    volumes:
      - ./backend/:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
      - 8080
    networks:
      - api

  client:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - api

networks:
  api:
    name: api