version: '3.6'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./dev.env
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
      - 8080:8080
    networks: 
      - api

networks:
  api:
    name: api